[package]
name = "ruft"
version = "0.1.0"
authors = ["MonadKai <onlookerliu_sjtu@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "0.8.1"